input_type: cartesian
encoder_type: BiGRU
attention_type: local
batch_size: 291
embedding_dim: 64
hidden_size: 64
lr: 0.001
mask: False
D: 5
min_freq: 3
num_layers: 1
rate_dropout: 0.5
teacher_force_ratio: 0.5
path: ./models/local/BiGRU_cartesian_loc_maskFalse.zip