input_type: cartesian
encoder_type: MLP
attention_type: local_recurrent
batch_size: 512
embedding_dim: 64
hidden_size: 64
mask: True
D: 5
min_freq: 3
num_layers: 1
rate_dropout: 0.5
teacher_force_ratio: 0.5
path : ./models/local_rec/MLP_cartesian_loc_rec_D=5_mask=True.zip